server:
  port: 2002
  servlet:
    context-path: /springcloud-eureka-server-2002
eureka:
  instance:
    hostname: eureka2002
  client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
             defaultZone: http://eureka2001:2001/eureka/,http://eureka2003:2003/eureka/