server:
  port: 80
  context-path: /springcloud-consumer
eureka:
  client:
    register-with-eureka: false #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone: http://localhost:2000/eureka