server:
  port: 1002
  context-path: /springcloud-provider
spring:
  application:
    name: springcloud-provider

eureka:
  instance:
    hostname: eureka2002
    appname:  springcloud-provider
    instance-id: springcloud-provider:1002
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2001:2001/eureka,http://eureka2002:2002/eureka,http://eureka2003:2003/eureka
